version: ~> 1.0

branches:
  only:
  - master

jobs:
  include:
  - language: nix
    env:
    - COQ=8.10
    script:
    - nix-build --argstr coq-version "${COQ}"

  - language: nix
    env:
    - COQ=8.11
    script:
    - nix-build --argstr coq-version "${COQ}"

  - dist: bionic
    language: minimal
    services:
    - docker
    env:
    - NJOBS="2"
    - CONTRIB_NAME="hb"
    - COQ="coqorg/coq:8.10" ELPI="coq-elpi.1.3.0" CMD="make && make install"
    install:
    - ./.travis.docker-install.sh
    script:
    - ./.travis.docker-test.sh
    after_script:
    - docker stop COQ

  - dist: bionic
    language: minimal
    services:
    - docker
    env:
    - NJOBS="2"
    - CONTRIB_NAME="hb"
    - COQ="coqorg/coq:8.11" ELPI="coq-elpi.1.3.1" CMD="make && make install"
    install:
    - ./.travis.docker-install.sh
    script:
    - ./.travis.docker-test.sh
    after_script:
    - docker stop COQ

  - dist: bionic
    language: minimal
    services:
    - docker
    env:
    - NJOBS="2"
    - CONTRIB_NAME="hb"
    - COQ="coqorg/coq:8.11" ELPI="coq-elpi.1.3.1" CMD="opam pin add coq-hierarchy-builder . -y -v"
    install:
    - ./.travis.docker-install.sh
    script:
    - ./.travis.docker-test.sh
    after_script:
    - docker stop COQ
