version: ~> 1.0

branches:
  only:
  - master
  - coq-master

env:
  global:
  - CONTRIB_NAME=hb
  - ELPI_811=coq-elpi.1.4.0
  - ELPI_DEV=https://github.com/LPCIC/coq-elpi.git#coq-master

jobs:
  include:

  - language: nix
    env:
    - COQ=8.11
    script:
    - nix-build --argstr coq-version "${COQ}"

  - dist: bionic
    language: minimal
    services:
    - docker
    env:
    - COQ=8.11 ELPI="install ${ELPI_811}" CMD="make && make install"
    install:
    - ./.travis/docker-install.sh
    script:
    - ./.travis/docker-test.sh
    after_script:
    - docker stop COQ

  - dist: bionic
    language: minimal
    services:
    - docker
    env:
    - COQ=8.11 ELPI="install ${ELPI_811}" CMD="opam pin add coq-hierarchy-builder ."
    install:
    - ./.travis/docker-install.sh
    script:
    - ./.travis/docker-test.sh
    after_script:
    - docker stop COQ

  - if: branch = coq-master
    dist: bionic
    language: minimal
    services:
    - docker
    env:
    - COQ=dev ELPI="pin add coq-elpi ${ELPI_DEV}" CMD="opam pin add coq-hierarchy-builder ."
    install:
    - ./.travis/docker-install.sh
    script:
    - ./.travis/docker-test.sh
    after_script:
    - docker stop COQ
